### ISSUE TITLE
Error in post: I didn’t author react basic hooks :)

### ISSUE THREAD

**Issue by paf31** [xc-jp/blog-posts#8]
I spotted [this post](https://github.com/xc-jp/blog-posts/blob/master/PureScript-React.md) on Hacker News. Nice post! But I wanted to clear up that I was not an author on the hooks library. I worked on the original react basic bindings but, while I'd love to be able to claim credit for it (it's a wonderful API design), the hooks variant was all @spicydonuts work.

**Comment by jamesdbrock** [comment]
Ok thanks I'll change that.

**Comment by jamesdbrock** [comment]
Done, thanks for reading!
